services:
  db:
    image: postgres:14.9
    ports:
      - 5432:5432
    command: postgres -D /var/lib/postgresql/data -F -c logging_collector=on -p 5432
    volumes:
      - ./data/dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ea_dev
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data
      LOGGING_COLLECTOR: 'on'